<!-- header -->
<div id="appHeader">
	<!-- logo -->
	<h1 class="logo"><a href="#">Marriott.com</a></h1>
	<a href="#" class="select1" name="select1">Testing<span></span></a>
	<!-- select-drop -->
	<div class="select-drop hotel-selector" id="leadFilter">
	<?php echo $hotel_dropdown_html; ?>
	</div>
	<!-- addnav -->
	<ul class="addnav">
		<li>Signed in as <?php echo $logged_in_as; ?>. (<a href="/index.php/LoginController/logout">Sign Out</a>)</li>
		<li><a href="#" class="cc_list">CC List</a></li>
		<li><a href="#">Help</a></li>
	</ul>
</div>